"""initial schema

Revision ID: 27b5fe506c91
Revises: 
Create Date: 2026-10-06 12:28:11.280323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27b5fe506c91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'editor', name='admin_role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_pending_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_last_used_step', sa.BigInteger(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='post_status', native_enum=False, length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_blog_posts_status_published', 'blog_posts', ['status', 'published_at'], unique=False)
    op.create_table('book_series',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capital', sa.String(length=200), nullable=True),
    sa.Column('timezones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('discount_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('percent', 'fixed', name='discount_kind', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemptions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind <> 'percent' OR value <= 100", name='ck_discount_percent_max'),
    sa.CheckConstraint('value > 0', name='ck_discount_value_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('free_reading_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sun_sign', sa.String(length=32), nullable=False),
    sa.Column('year_animal', sa.String(length=32), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_free_requests_created', 'free_reading_requests', ['created_at'], unique=False)
    op.create_table('free_readings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('sign', 'animal', name='free_reading_kind', native_enum=False, length=32), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'key', 'locale', name='uq_free_reading')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='job_status', native_enum=False, length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_at'], unique=False)
    op.create_index('ix_jobs_payload_order_id', 'jobs', [sa.literal_column("(payload->>'order_id')")], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_email_created', 'login_attempts', ['email', 'created_at'], unique=False)
    op.create_index('ix_login_attempts_ip_created', 'login_attempts', ['ip', 'created_at'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('site_content',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'locale', name='uq_site_content_key_locale')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('series_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('purchase_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['book_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'slug', name='uq_book_series_slug')
    )
    op.create_table('cities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ascii_name', sa.String(length=200), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('admin1', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('is_capital', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cities_capital', 'cities', ['country_code'], unique=False, postgresql_where=sa.text('is_capital'))
    op.create_index('ix_cities_country_ascii', 'cities', ['country_code', 'ascii_name'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('discount_code_id', sa.BigInteger(), nullable=True),
    sa.Column('show_banner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('system_instruction', sa.Text(), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='prompt_status', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('slot BETWEEN 1 AND 6', name='ck_prompt_slot_range'),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot', 'version', name='uq_prompt_slot_version')
    )
    op.create_index('uq_prompt_one_published_per_slot', 'prompt_versions', ['slot'], unique=True, postgresql_where=sa.text("status = 'published'"))
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('awaiting_payment', 'paid', 'queued', 'generating', 'ready', 'generation_failed', 'expired', 'abandoned', 'refunded', name='order_status', native_enum=False, length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_time', sa.Time(), nullable=True),
    sa.Column('time_fold', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('place_label', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('birth_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chart', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calc_version', sa.String(length=32), nullable=False),
    sa.Column('list_price_cents', sa.Integer(), nullable=False),
    sa.Column('discount_code_id', sa.BigInteger(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_provider', sa.String(length=32), nullable=False),
    sa.Column('provider_session_id', sa.String(length=255), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_version_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('personal_data_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_order_amount_nonneg'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_session_id')
    )
    op.create_index('ix_orders_email', 'orders', ['email'], unique=False)
    op.create_index('ix_orders_provider_payment_id', 'orders', ['provider_payment_id'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_payment_event')
    )
    op.create_table('report_sections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='section_status', native_enum=False, length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'slot', name='uq_report_section_order_slot')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('email_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_download_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('ix_reports_expires', 'reports', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_expires', table_name='reports')
    op.drop_table('reports')
    op.drop_table('report_sections')
    op.drop_table('payment_events')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index('ix_orders_provider_payment_id', table_name='orders')
    op.drop_index('ix_orders_email', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_prompt_one_published_per_slot', table_name='prompt_versions', postgresql_where=sa.text("status = 'published'"))
    op.drop_table('prompt_versions')
    op.drop_table('offers')
    op.drop_index('ix_cities_country_ascii', table_name='cities')
    op.drop_index('ix_cities_capital', table_name='cities', postgresql_where=sa.text('is_capital'))
    op.drop_table('cities')
    op.drop_table('books')
    op.drop_index('ix_audit_logs_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_sessions')
    op.drop_table('site_content')
    op.drop_table('settings')
    op.drop_table('media')
    op.drop_index('ix_login_attempts_ip_created', table_name='login_attempts')
    op.drop_index('ix_login_attempts_email_created', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('ix_jobs_payload_order_id', table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('free_readings')
    op.drop_index('ix_free_requests_created', table_name='free_reading_requests')
    op.drop_table('free_reading_requests')
    op.drop_table('discount_codes')
    op.drop_table('countries')
    op.drop_table('book_series')
    op.drop_index('ix_blog_posts_status_published', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
